version: 2
jobs:
  build:
    parallelism: 3
    working_directory: ~/circle-ci-demo-rails4
    docker:
      - image: circleci/ruby:2.3-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          MYSQL_HOST: 127.0.0.1
          MYSQL_PASSWORD: ''
          RAILS_ENV: test
      - image: circleci/mysql:5.6
        environment:
          MYSQL_USER: root
          MYSQL_DATABASE: circle-ci-demo-rails4_test
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    steps:
      - checkout
      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v
      - save_cache:
          key: circle-ci-demo-rails4-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      # Restore bundle cache
      - restore_cache:
          keys:
            - circle-ci-demo-rails4-{{ checksum "Gemfile.lock" }}
            - circle-ci-demo-rails4-
      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundle
      # Database setup
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Database setup
          command: rake db:schema:load --trace
      - run:
          name: Setting secrets.yml
          command: mv -f config/secrets.ci.yml config/secrets.yml
      - run:
          name: Run Rspec
          command: |
            bundle exec rspec --profile 10 \
                    --format RspecJunitFormatter \
                    --out test_results/rspec.xml \
                    --format progress \
                    $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      # Save test results for timing analysis
      - store_test_results:
          path: test_results
